server:
  port: 8080
  tomcat:
    basedir: /seckilling/tomcat_logs/
    accesslog:
      enabled: true
      pattern: "%h %t %r %s %b %T"

mybatis:
 configuration:
  map-underscore-to-camel-case: true
#  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #若是想调试sql以及查看sql语句请把这个配置打开

logging:
  config: classpath:logback-spring.xml

deng:
  rabbitmq:
      addresses: localhost
      port: 5672
      username: guest
      password: guest
      virtual: seckilling


spring:
 datasource:
   url: jdbc:mysql://localhost:3306/seckilling_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
   username: root
   password: smile
   driver-class-name: com.mysql.cj.jdbc.Driver

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params=count: countSql