server:
  port: 8080
  tomcat:
    basedir: /seckilling/tomcat_logs/
    accesslog:
      enabled: true
      pattern: "%h %t %r %s %b %T"

mybatis:
 configuration:
  map-underscore-to-camel-case: true

logging:
  config: classpath:logback-spring.xml


spring:
 datasource:
   url: jdbc:mysql://localhost:3306/seckilling_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
   username: root
   password: smile
   driver-class-name: com.mysql.cj.jdbc.Driver

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params=count: countSql